services:
  uptime-kuma:
    container_name: uptime-kuma
    image: louislam/uptime-kuma:1
    ports:
        - 3001:3001
    restart: always
    volumes:
        - ${DOCKERDATADIR}/uptimekuma:/app/data